---
title: "TeamProject2"
author: "Mario Prata Dias Alvarez, Sophie Kate Edelman, Meghan Sarah Hoffman, Elias Florentin John, Kritika Singh, Benjamin Victor Tward"
date: "2025-10-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("tidyverse")
library(tidyverse)
library(caret)
#install.packages("recipes")
library(recipes)
```

## Step 0: Why?

## Step 1: Load the Data

```{r}
songs <- read.csv("Spotify.csv", stringsAsFactors = T)
```

## Step 2: Clean the Data

```{r}
str(songs)
summary(songs)
songs = songs |>
  select(-c(X, track_id, album_name, track_name, artists)) 
# If we wanted to incorporate artist popularity, we would not delete artists
# For now, we can look at naive approach to consider all artists to be equal playing field

songs |> glimpse()
```



## Step 3: Split the Data


```{r}
n = nrow(songs)
p = .7

set.seed(12345)
ind = sample(1:n, n*p)
train = songs[ind,]
test = songs[-ind,]


rec = recipe(popularity ~ ., data = train) |>
  step_impute_median(all_numeric_predictors()) |> 
  step_normalize(all_numeric_predictors()) |>
  step_dummy(all_nominal_predictors())

prep_rec = prep(rec, training = train)

X_train = bake(prep_rec, new_data = train, all_predictors())
X_test  = bake(prep_rec, new_data = test, all_predictors())
y_train = train$popularity
y_test  = test$popularity

X_train = as.matrix(X_train)
X_test  = as.matrix(X_test)
y_train = as.numeric(y_train)
y_test  = as.numeric(y_test)
```

## Step 4: Train the Data
```{r}
m1 <- lm(popularity ~ ., data = train)
```



## Step 5: Test the Data

## Step 